language: php

before_script:
  - sudo apt-get update
  - sudo apt-get install -y openoffice.org openoffice.org-writer unoconv
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

php:
  - 5.3
  - 5.4
